# Generated by Django 6.0.3 on 2026-03-06 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estagiario', models.CharField(max_length=200, verbose_name='Nome do(a) estagiário(a)')),
                ('empresa', models.CharField(max_length=250, verbose_name='Razão social ou nome fantasia da empresa')),
                ('instituicao_ensino', models.CharField(max_length=250, verbose_name='Nome da escola ou faculdade')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluída'), ('SLR', 'Somente o link foi respondido'), ('ESE', 'Estagiário(a) saiu da empresa')], max_length=3)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoSemestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('data_prevista', models.DateField()),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='avaliacoes_pdfs/')),
                ('avaliacao_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_semestrais', to='avaliacao.avaliacao')),
            ],
        ),
    ]
