# Generated by Django 6.0.3 on 2026-03-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data_rescisao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Rescisão'),
        ),
    ]
