# Generated by Django 6.0.3 on 2026-03-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_avaliacao_data_rescisao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaosemestral',
            options={'ordering': ['data_prevista']},
        ),
    ]
