# Generated by Django 6.0.3 on 2026-03-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_alter_avaliacaosemestral_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluída'), ('SLR', 'Somente o link foi respondido'), ('ESE', 'Estagiário(a) saiu da empresa'), ('APZ', 'Assinatura pendente no ZapSign')], max_length=3),
        ),
    ]
