# Generated by Django 6.0.3 on 2026-03-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_alter_avaliacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone celular do(a) estagiário(a)'),
        ),
    ]
