# Generated by Django 6.0.3 on 2026-04-23 20:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0005_avaliacao_telefone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAvaliacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome_estagiario', models.CharField(max_length=200, verbose_name='Nome do(a) estagiário(a)')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone celular do(a) estagiário(a)')),
                ('empresa', models.CharField(max_length=250, verbose_name='Razão social ou nome fantasia da empresa')),
                ('instituicao_ensino', models.CharField(max_length=250, verbose_name='Nome da escola ou faculdade')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_rescisao', models.DateField(blank=True, null=True, verbose_name='Data de Rescisão')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluída'), ('SLR', 'Somente o link foi respondido'), ('ESE', 'Estagiário(a) saiu da empresa'), ('APZ', 'Assinatura pendente no ZapSign')], max_length=3)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical avaliacao',
                'verbose_name_plural': 'historical avaliacaos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
