# Generated by Django 6.0.3 on 2026-06-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0006_historicalavaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('P', 'Pendente'), ('C', 'Concluída'), ('SLR', 'Somente o link foi respondido'), ('ESE', 'Estagiário(a) saiu da empresa'), ('APZ', 'Assinatura pendente no ZapSign')], max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalavaliacao',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('P', 'Pendente'), ('C', 'Concluída'), ('SLR', 'Somente o link foi respondido'), ('ESE', 'Estagiário(a) saiu da empresa'), ('APZ', 'Assinatura pendente no ZapSign')], max_length=3),
        ),
    ]
